Repository ManhQuynhDev/DemoGitHub, pull requests merged in 2023-12, with the labels that each got.

#1 Update
  app/src/main/java/fpoly/group6_pro1122/myapplication/SecondActivity.kt
Labels: bug

#3 Update XML
  app/src/main/java/fpoly/group6_pro1122/myapplication/SecondActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: documentation

#4 Update XMl past 2
  app/src/main/res/layout/activity_main.xml
Labels: enhancement
